In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [4]:
data5 = pd.read_pickle('d_part_05.pkl')#part 
# Key - 'N'
# 

In [5]:
for keys in data5.keys():
    print(keys)

FRONT_TOPROLL_SD0526A239420114_008_STYLE
1670177_2941632X _TESLA_MY_DR_BELTLINE_2_0_FR_LH
2089738X_TOP_ROLL_FRT_KISS_CUT_RH_STYLE
2237373X_TOP_ROLL_FRT_COVRD_LH_ALLCATPART
PSA_C48E_THERMOCOVERED_TOPROLL_ALLCATPART


In [12]:
data5['FRONT_TOPROLL_SD0526A239420114_008_STYLE']['N']

array([[ 0.01690266, -0.92995083, -0.36729541],
       [ 0.01690266, -0.92995083, -0.36729541],
       [ 0.01690266, -0.92995083, -0.36729541],
       ...,
       [ 0.06108081, -0.49811602,  0.86495638],
       [ 0.05600601, -0.76223534,  0.64487249],
       [ 0.04273998, -0.92881197,  0.36807832]])

In [5]:
# def arrays_vstack(filename):
#     for i in range(len(data5[filename]['pnts'])):
#         if i ==0:
#             array_used_in_loop = data5[filename]['pnts'][i]
#         else :
#             array_used_in_loop = np.vstack((array_used_in_loop , data5[filename]['pnts'][i]))
    
#     return array_used_in_loop

In [22]:
array1 = np.round(data5['FRONT_TOPROLL_SD0526A239420114_008_STYLE']['N'],3)
array2 = np.round(data5['1670177_2941632X _TESLA_MY_DR_BELTLINE_2_0_FR_LH']['N'],3)
array3 = np.round(data5['2089738X_TOP_ROLL_FRT_KISS_CUT_RH_STYLE']['N'],3)
array4 = np.round(data5['2237373X_TOP_ROLL_FRT_COVRD_LH_ALLCATPART']['N'],3)
array5 = np.round(data5['PSA_C48E_THERMOCOVERED_TOPROLL_ALLCATPART']['N'],3)

In [23]:
print(len(array1),len(array2),len(array3),len(array4),len(array5))

5616 7952 9520 15840 14648


In [24]:
array1

array([[ 0.017, -0.93 , -0.367],
       [ 0.017, -0.93 , -0.367],
       [ 0.017, -0.93 , -0.367],
       ...,
       [ 0.061, -0.498,  0.865],
       [ 0.056, -0.762,  0.645],
       [ 0.043, -0.929,  0.368]])

## uni1

In [34]:
uni, count = np.unique(array1, axis = 0,return_counts=True)

In [35]:
np.where(count == max(count))

(array([3542], dtype=int64),)

In [37]:
print (uni[3542])
print(count[3542])

[ 0.137 -0.07   0.988]
12


## Uni2 

In [38]:
uni2, count2 = np.unique(array2, axis = 0,return_counts=True)

In [39]:
np.where(count2 == max(count2))

(array([86], dtype=int64),)

In [40]:
print (uni2[86])
print(count2[86])

[-0.97  -0.122  0.21 ]
33


## Uni3

In [42]:
uni3, count3 = np.unique(array3, axis = 0,return_counts=True)

In [43]:
np.where(count3 == max(count3))

(array([56], dtype=int64),)

In [45]:
print(uni3[56])
count3[56]

[-0.964  0.122  0.236]


13

## Uni4 

In [46]:
uni4, count4 = np.unique(array4, axis = 0,return_counts=True)

In [47]:
np.where(count4 == max(count4))

(array([12298], dtype=int64),)

In [48]:
print(uni4[12298])
count4[12298]

[ 0.957  0.124 -0.261]


46

## uni5 

In [49]:
uni5, count5 = np.unique(array5, axis = 0,return_counts=True)

In [50]:
np.where(count5 == max(count5))

(array([5933], dtype=int64),)

In [51]:
count5[5933]

186

In [52]:
uni5[5933]

array([ 0.023,  0.998, -0.057])